config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses

  get '/allexpense/:id', as: :allexpense ,to: 'expenses#allexpense'

  resources :preferences, only: [:show, :update]

  resources :user_budgets

  authenticated :user do
    root to: 'expenses#index', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'pages#show', id: 'home', as: :unauthenticated_root
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :expense
  has_many :user_budget

  # gender
  GENDER_TYPES = ["Gender","Male", "Female"]

end

# == Schema Information
#
# Table name: users
#
#  id                     :uuid            not null, primary key
#  email                  :string          default(""), not null
#  encrypted_password     :string          default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  firstname              :string(250)
#  lastname               :string(250)
#  created_at             :datetime
#  updated_at             :datetime
#

app/views/users/shared/_links.html.erb
<br><br>
<%- if controller_name != 'sessions' %>
  <%= link_to raw('<i class="fa fa-sign-in"></i> Log In'), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to raw('<i class="fa fa-user-plus"></i> Sign Up'), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_right_board.html.erb
<div class="col-xs-8 right-board">
  <h1><i class="fa fa-inr"></i> Spendit !</h1>
  <h4>An Simple and yet powerful expense tracking app. </h4>
</div>