config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenses

  get '/allexpense/:id', as: :allexpense ,to: 'expenses#allexpense'

  resources :preferences, only: [:show, :update]

  resources :user_budgets

  authenticated :user do
    root to: 'expenses#index', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'pages#show', id: 'home', as: :unauthenticated_root
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    expense_details
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    expense_details
  end

  # Show all expenses
  def allexpense
    @months = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    @expense = Expense.all.where(user_id: current_user.id).group_by { |m| m.created_at.month }
    expense_details
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    expense_details
  end

  # GET /expenses/1/edit
  def edit
    expense_details
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.user_id = current_user.id if current_user
    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense }
        flash[:success] = "Expense was success created."
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      @expense.user_id = current_user.id if current_user
      if @expense.update(expense_params)
        format.html { redirect_to @expense }
        flash[:success] = "Expense was success updated."
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
      flash[:warning] = "Expense was success deleted."
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :amount)
    end

end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_budget_pane.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3> Budget Pane </h3>
  <% if @next_month_budget %>
    <%= simple_form_for @user_budget do |f| %>
      <%= f.input :month, :as => :hidden, :input_html => { :value => "next" } %>
      <%= f.input :budget, wrapper_html: { class: 'form-group' }, placeholder: 'Your budget for next month', input_html: { class: 'form-control' }, error: 'Update your budget for next month' %>
      <%= f.button :submit, class: 'btn btn-success' %>
    <% end %>
  <% end %>
  <br>
  <% if @this_month_budget %>
    <%= simple_form_for @user_budget do |f| %>
      <%= f.input :month, :as => :hidden, :input_html => { :value => "this" } %>
      <%= f.input :budget, wrapper_html: { class: 'form-group' }, placeholder: 'Your budget for this month', input_html: { class: 'form-control' }, error: 'Update your budget for this month' %>
      <%= f.button :submit, class: 'btn btn-success', value: "Fix your budget" %>
    <% end %>
  <% else %>
    <h5> Your budget for this month is <br>₹ <%= @budget %> </h5>
    <%#= link_to raw("<i class='fa fa-pencil'></i> Edit") %>
  <% end %>
  </div>
</div>

app/views/expenses/_form.html.erb
<div class="col-xs-6">
  <%= form_for(@expense) do |f| %>
    <% if @expense.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

        <ul>
        <% @expense.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :title %><br>
      <%= f.text_area :title, class:"form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :amount %><br>
      <%= f.text_field :amount, class:"form-control" %>
    </div>
    <div class="actions">
      <%= f.submit 'update', :class=> "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/expenses/_sidemenu.html.erb
<div class="col-xs-3 side-menu">
  <h1><%= link_to raw('<i class="fa fa-inr"></i> Spendit'), root_path, class: "lead" %></h1>
  <h5>Household spending</h5>
  <div class="row">
    <div class="col-xs-3">
      <%#= image_tag("avatar_male.jpg", class: "img-circle profile-icon") %>
      <%= gravatar_image_tag(@current_user.email.gsub('spam', 'mdeering'), :alt => @current_user.email , class: "img-circle profile-icon") %>
    </div>
    <div class="col-xs-9">
      <% unless @current_user.firstname.blank? %>
        <p class="lead profile-name"><%= @current_user.firstname %> <%= @current_user.lastname %></p>
      <% else %>
        <p class="lead profile-name">Welcome, User</p>
        <%= link_to raw("<i class='fa fa-cog'></i> Update Settings"), preference_path(@current_user), method: :get, :class => 'navbar-link'  %><br>

      <% end %>
    </div>
  </div>
  <div class="spent-remaining">
    <h3 class="spent"><i class="fa fa-inr"></i> <%= @total_expenses %></h3>
    <% unless @budget.nil? %>
      <h3 class="remaining"><i class="fa fa-inr"></i> <%= @budget - @total_expenses %></h3>
    <% end %>
  </div>

  <%#= link_to raw("<i class='fa fa-pencil'></i> Edit profile"), preference_path(@current_user.id), :class => 'navbar-link' %> <br>
  <%= link_to raw("<i class='fa fa-th-list'></i>  All Expense"), allexpense_path(@current_user), method: :get, :class => 'navbar-link'  %><br>
  <%= link_to raw("<i class='fa fa-cog'></i> Settings"), preference_path(@current_user), method: :get, :class => 'navbar-link'  %><br>
  <%= link_to raw("<i class='fa fa-sign-out'></i> Logout"), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
</div>

app/views/expenses/allexpense.html.erb
<div class="col-xs-6 expense-pane">

  <% @expense.each do |format|%>
    <% m = format[0] %>
    <h2>Expenses on <%= @months[m] %> <br>
    <% monthly_budget = get_budget_by_month_year(m, format[1].first.created_at.year) %>
    <% monthly_expense = get_all_month_expenses(m, format[1].first.created_at.year) %>
    <% if monthly_budget != "0" %>
      <%= monthly_budget %> - <span class="text-spent"><%= monthly_expense %></span> = <span class="text-remaining"><%= monthly_budget - monthly_expense %></span>
    <% end %>
    </h2><br>
    <% @monthly_expense = format[1] %>
    <table class="table">
      <thead>
        <tr><th>Title</th>
        <th>Amount</th>
        <th>Created By</th>
        <th>Date</th>
      </tr>
      </thead>
      <tbody>
    <% @monthly_expense.each do |month| %>
        <tr>
        <td><%= month.title %></td>
        <td><%= month.amount %></td>
        <% unless month.user.firstname.blank? %>
          <td><%= month.user.firstname %></td>
        <% else %>
          <td><%= month.user.email %></td>
        <% end %>
        <td><%= month.created_at.strftime("%B %d, %Y") %></td>
        </tr>
    <% end %>
      </tbody>
    </table>
    <hr>
  <% end %>
  <% if @expense.blank? %>
  <br><br>
   <p class="">Your slate is clean, you can add a new expense <%= link_to "here", new_expense_path %></p>
  <% end %>
</div>

app/views/expenses/edit.html.erb
<div class="col-xs-6 expense-pane">
  <h2>Expenses on <%= @date.strftime("%B") %></h2>
  <div class="row">
    <div class="col-xs-4">
      <i class="fa fa-calendar"></i> <%= @date.strftime("%B %d, %Y") %>
    </div>
    <div class="col-xs-8 text-right">
      <%= link_to raw('<i class="fa fa-plus"></i> Add New'), new_expense_path %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-2">
      <%= link_to raw('<i class="fa fa-arrow-left"></i> back'), root_path %>
    </div>
    <div class="col-xs-5">
      <p><i class="fa fa-pencil"></i> Editing Expense</p>
    </div>
  </div>
  <hr>
  <%= render 'form' %>


</div>

app/views/expenses/index.html.erb
  <div class="col-xs-6 expense-pane">
    <h2>Expenses on <%= @date.strftime("%B") %></h2>
    <div class="row">
      <div class="col-xs-4">
        <i class="fa fa-calendar"></i> <%= @date.strftime("%B %d, %Y") %>
      </div>
      <div class="col-xs-8 text-right">
        <%= link_to raw('<i class="fa fa-plus"></i> Add New'), new_expense_path %>
      </div>
    </div>


    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Amount</th>
          <th>Created by</th>
          <th>Date</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% unless @expenses[@month].nil? %>
          <% @expenses[@month].each do |expense| %>
            <tr>
              <td><%= expense.title %></td>
              <td><i class="fa fa-inr"></i> <%= expense.amount %></td>
              <% unless expense.user.firstname.blank? %>
                <td><%= expense.user.firstname %></td>
              <% else %>
                <td><%= expense.user.email %></td>
              <% end %>
              <td><%= expense.created_at.strftime("%B %d, %Y") %></td>
              <!-- <td><%= link_to raw('<i class="fa fa-eye"></i>'), expense %></td> -->
              <% if expense.user.email == @current_user.email %>
                <td><%= link_to raw('<i class="fa fa-pencil"></i>'), edit_expense_path(expense) %></td>
                <td><%= link_to raw('<i class="fa fa-trash"></i>'), expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% else %>
                <td><td>
                <td><td>
              <% end %>
            </tr>
          <% end %>
        <% else %>
          <tr><td><p class="text-small">No Expenses found.</p></td></tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <br><br>
  </div>

app/views/expenses/new.html.erb
<div class="col-xs-6 expense-pane">
  <h2>Expenses on <%= @date.strftime("%B") %></h2>
  <h6><i class="fa fa-calendar"></i> <%= @date.strftime("%B %d, %Y") %></h6>



  <hr>
      <%= link_to raw('<i class="fa fa-arrow-left"></i> Back'), root_path %> - Add New Expense
  <hr>
  <%= render 'form' %>

</div>

app/views/expenses/show.html.erb
<div class="col-xs-6 expense-pane">
  <h2>Expenses on <%= @date.strftime("%B") %></h2>
  <div class="row">
    <div class="col-xs-4">
      <i class="fa fa-calendar"></i> <%= @date.strftime("%B %d, %Y") %>
    </div>
    <div class="col-xs-8 text-right">
      <%= link_to raw('<i class="fa fa-plus"></i> Add New'), new_expense_path %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-2">
      <%= link_to raw('<i class="fa fa-arrow-left"></i> Back'), root_path %>
    </div>
    <div class="col-xs-2">
      <%= link_to raw('<i class="fa fa-pencil"></i> Edit'), edit_expense_path(@expense) %>
    </div>
  </div>
  <hr>
  <p>
    <strong>Title:</strong>
    <%= @expense.title %>
  </p>

  <p>
    <strong>Amount:</strong>
    ₹<%= @expense.amount %>
  </p>



</div>